# Generated by Django 3.1.1 on 2020-10-03 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('groupImageUrl', models.CharField(blank=True, max_length=50, null=True)),
                ('userlist', models.ManyToManyField(through='api.UserGroupMember', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['gid'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('companyid', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('imageurl', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('group_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usergroups')),
                ('user_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pid'],
            },
        ),
        migrations.AddField(
            model_name='usergroupmember',
            name='group_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usergroups'),
        ),
        migrations.AddField(
            model_name='usergroupmember',
            name='user_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
