# Generated by Django 3.1.1 on 2020-09-29 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('companyid', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('imageurl', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
    ]
